name: Eslinter Fix and Push CI

on:
  push:
    branches:
      - "*"

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v1
          with:
            node-version: "14.x"

        - name: Install dependencies
          run: npm install

        - name: Fix Eslint issues
          run: npm run eslint:fix

        - name: Commit changes
          run: |
            git config user.name github-actions[bot]
            git config user.email github-actions[bot]@users.noreply.github.com
            git commit -am "fixed Eslint issues" || true

        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}

        - name: Check again to validate all issues are fixed
          run: npm run eslint
